[tool.poetry]
name = "python-wikibase"
version = "0.1.0"
description = ""
authors = ["Samuel Meuli <me@samuelmeuli.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
